# Generated by Django 3.0.8 on 2020-10-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200914_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='licenses_remaining',
        ),
        migrations.AlterField(
            model_name='license',
            name='on_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Soldier'),
        ),
    ]
