# Generated by Django 3.0.8 on 2020-10-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201005_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='pub_date',
        ),
    ]
